---
title: "Trials For Paper on Entropy of Ordinal Vars"
author: "Wendy Olsen"
date: "22 August 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C:/data/AsianBaro")
```

## R Markdown

```{r Trial1}
#Use discretizeDF.supervised found in 
install.packages("arulesCBA")
library(arulesCBA)
library(haven)
library(tidyverse)
#From this point, the verb discretize has a conflict between arulesCBA and entropy package.  However, we can use discretizeDF.supervised from arulesCBA without a conflict.
         #* IMPORTANT *#
#*note, you must run the Asian barometers v7 entropy tests RMD programme first.
#*
#*
#*
#*
#*Step 1.  for Table of Bivariate Results
str(age_encoded)
str(edu_encoded)
dftest<-data.frame(cbind(data.frame(q63_encoded), data.frame(age_encoded), abindia$Q63))
#basically, R is awkward - prev programme _v7base.Rmd has created some issues; some of the vector names are using illicit characters. (.) Below, we will rename these. 

#* INTERLUDE on SIMULATION
#generate education simulation multinomial
pr<-c(30,10,12,26,22)
edusim <- data.frame(rmultinom(1000, 5318, pr))
#It emulates education in five levels from the Asian Barometers, unweighted.
summary(edusim)
str(edusim)
#It emulates education in five levels from the Asian Barometers, unweighted.
edusimt <- data.frame(t(edusim))
str(edusimt)
#Write the samples out to use elsewhere as a simulation of education only.
edtmp <- tempfile(fileext = ".dta")
#Note- using haven package, we have to type in the whole file path!
write_dta(edusimt,  "C:/data/AsianBaro/data/edtmp" )
```



```{r step2sendvarstoStata}
summary(df_edu)
edu1_encoded<- edu_encoded
summary(edu1_encoded)
summary(edu2_encoded)
names(edu1_encoded)<-c("edu1_1", "edu1_2", "edu1_3", "edu1_4","edu1_5")
str(edu1_encoded)
names(edu2_encoded)<-c("edu2_1", "edu2_2", "edu2_3", "edu2_4","edu2_5")
str(edu1_encoded)

age <- abindia$Se3_1
summary(age)
age_encoded <- matrix(0, nrow = length(age), ncol = num_bins)
for (i in 1:length(age)) {
  age_encoded[i, age_bins[i]] <- 1
}

colnames(age_encoded) <- c("age18to26","age27to34","age35to42","age43to50","age51to58","age59to66","age67to74","age75to82","age83to90","age91to98")
summary(age_encoded)
IDnumber<-abindia$IDnumber
blocAB<-cbind(IDnumber,df_edu,edu1_encoded,edu2_encoded,age_encoded, age)
str(blocAB)
summary(blocAB)

#This is a set of 3 working commands which tell Haven to send the tmp.dta file out to stata to use. 
df<-blocAB
tmpAgeEduc <- tempfile(fileext = ".dta")
#In R, the working directory won't be used in the write_dta command.
#This appears to be a novelty of Haven, the package used for write_dta.
#Therefore, specify the whole file path for the temporary dta file! 
write_dta(df, "C:/data/AsianBaro/data/tmpAgeEduc.dta")

#tmp <- tempfile(fileext = ".dta")
#write_dta(df, tmp)
#write_dta("q63age", q63age) #path comes first.  Then the object which is source.
#none of the above works , due to non comparability of labels in the vectors. 
#write_dta(df, "/data/tmp")
#That has worked.  The file tmp.dta has appeared in the right place. 
```

## Including Plots

Comments here go into the report.

```{r nameofnextchunk, echo=FALSE}
plot(df_edu$Edu)

```
